# Generated by Django 5.0.6 on 2024-06-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_type_expense_delete_expenses_delete_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Transiction',
        ),
    ]
