# Generated by Django 5.0.6 on 2024-06-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_income_remove_transiction_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Income',
            new_name='ExpenseM',
        ),
        migrations.RenameModel(
            old_name='Expense',
            new_name='IncomeM',
        ),
    ]
