# Generated by Django 5.0.6 on 2024-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_income_expensem_rename_expense_incomem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensem',
            name='Sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomem',
            name='Sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expensem',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incomem',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
